name: "myflow"
startNode: "startNode"
middleNode: 
  - "middleNode1, middleNode2, middleNode1, middleNode2"
  - "middleNode2, middleNode3, middleNode2, endNode"
  - "middleNode3, endNode, middleNode2, endNode"
endNode: "endNode"
